export const INFO_TIPS = {
  topK: 'How many documents to return after fusion. Range is 1–50.',
  alpha: 'Blend of BM25 and vector. 0 is all lexical, 1 is all dense, 0.50 is an even mix.',
  minVector: 'Drop documents whose raw vector score is below this. 0 turns the gate off.',
  dataset: 'Which corpus to search: Wikipedia, Kearney contracts, or both.',
  normalisation:
    'How BM25 and vector scores are put on one scale before they mix. Min-max stretches each list to 0–1. Z-score uses mean and spread. RRF ignores raw scores and uses ranks.',
  rrfK: 'Score is 1/(k + rank). You type k; nothing is pre-filled. Small k favours the top ranks (0 is 1/rank). Large k flattens the gaps so mid-ranks stay competitive.',
  sourceContains: 'Keep documents whose source path or URL contains this text.',
  createdFrom: 'Inclusive start of the document created-at filter.',
  createdTo: 'Inclusive end of the document created-at filter.',
  p50: 'Median search time in this window. Half of requests were faster.',
  p95: '95th percentile search time. Only 5% of requests were slower.',
  totalRequests: 'Searches recorded in the selected window.',
  zeroResults: 'Searches in this window that returned no documents.',
  timeWindow: 'Time range for the tiles, volume chart, and tables.',
  probeQuery: 'Query text sent in every concurrent hit of the latency burst.',
  concurrentHits: 'How many searches start at the same instant. Range is 2–200.',
  probeDataset: 'Optional corpus restriction for the burst. Empty searches both.',
  burstSent: 'Hits the API started versus how many finished without error.',
  burstFailed: 'Hits that raised or returned an error in this burst.',
  burstP50: 'Median latency of the hits in this burst, not the dashboard window.',
  burstP95: '95th percentile latency of the hits in this burst.',
  burstAvg: 'Mean latency of the hits in this burst.',
  burstWall: 'Wall-clock time from firing the burst until the last hit finished.',
  ndcg10: 'Discounted gain at rank 10. Higher means relevant documents sat higher.',
  recall10: 'Fraction of relevant documents found in the top 10.',
  mrr10: 'Mean reciprocal rank of the first relevant hit, cutoff 10.',
  evalAlpha: 'BM25 versus vector mix used for that experiment run.',
  evalNorm: 'Score scaling used before fusion on that run.',
  evalModel: 'Embedding model name recorded for that run.',
  evalPreprocess: 'Text-cleaning flags recorded for that run.',
  evalN: 'Number of judged queries scored in that run.',
  evalTag: 'Label you gave the run so you can find it later.',
  evalCommit: 'Git commit recorded when the run was scored.',
  evalTimestamp: 'When the experiment row was written.',
  evalMetric: 'Which ranking metric the chart plots across runs.',
  severity: 'Log level to include. “all” shows every level, not only errors.',
  logFrom: 'Inclusive start of the log created-at range.',
  logTo: 'Inclusive end of the log created-at range.',
  logLimit: 'Maximum number of log rows to fetch. Range is 1–100.',
  apiStatus: 'Whether the API process is up and answering /health.',
  version: 'App version string reported by the server.',
  commit: 'Git commit the server was built from.',
  indexModel: 'Sentence-transformers model used to embed documents.',
  documents: 'Number of documents currently in the loaded index.',
  embeddingDim: 'Width of each document embedding vector.',
  builtAt: 'When the FAISS and BM25 indexes were last built.',
  corpusHash: 'Hash of the ingested corpus, so you can tell if the index matches the files.',
  indexMissing: 'No index is loaded. Search will fail until documents are indexed.',
  cgFiles: 'Source files scanned into this call graph.',
  cgFunctions: 'Functions found in those files.',
  cgUncalledFiles: 'Files with no inbound call from the scanned set. These start the BFS.',
  cgUncalledFunctions: 'Functions nobody in the scanned set calls.',
  cgFileEdges: 'File-to-file edges from imports and references.',
  cgCallEdges: 'Function-to-function call edges.',
  rank: 'Position in the fused result list. 1 is the best match.',
  hybrid: 'Combined BM25 + vector score after normalisation, or RRF if that mode is on.',
  bm25: 'Lexical match score from BM25. The bar uses the normalised value; hover the bar for the raw score.',
  vector: 'Cosine similarity from the document embedding. The bar uses the normalised value.',
  closest: 'Nearest query-like word in the document (semantic highlight). Not a ranking signal.',
} as const

export type InfoTipKey = keyof typeof INFO_TIPS
